name: Test against PR

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4.3.0
              with:
                  node-version: 20

            - name: Cache npm dependencies
              uses: actions/cache@v2
              with:
                  path: '~/.npm'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install modules
              run: npm ci

            - name: Run tests
              run: npm run test
    build-container:
        runs-on: ubuntu-latest
        needs: test
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0

            - name: Build Docker image
              uses: docker/build-push-action@v6.15.0
              with:
                  context: .
                  push: false
