name: Release

on:
    release:
        types: published

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    test-build-release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            # Setup
            - uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4.3.0
              with:
                  node-version: 22

            - name: Cache npm dependencies
              uses: actions/cache@v4.2.3
              with:
                  path: '~/.npm'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install modules
              run: npm ci

            # Test
            - name: Run tests
              run: npm run test

            # Build docker image, push to GitHub Packages
            - name: Log in to the Container registry
              uses: docker/login-action@v3.4.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5.7.0
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=tag
                      type=sha

            - name: Build and push Docker image
              uses: docker/build-push-action@v6.15.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
